Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
