services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

test: &test
  stage: test
  language: ruby
  before_install:
    - gem install bundler
    - gem update --system

jobs:
  include:
    - <<: *test
      rvm: 2.6.3
    - <<: *test
      rvm: 2.5.5
    - <<: *test
      rvm: 2.4.6

    - stage: coditsu
      language: ruby
      rvm: 2.6.3
      before_install:
        - gem update --system
        - gem install bundler
      before_script:
        - docker create -v /sources --name sources alpine:3.4 /bin/true
        - docker cp ./ sources:/sources
      script: >
        docker run
        -e CODITSU_API_KEY
        -e CODITSU_API_SECRET
        -e CODITSU_REPOSITORY_ID
        -e CODITSU_BUILD_BRANCH=$TRAVIS_BRANCH
        --volumes-from sources
        coditsu/build-runner:latest

stages:
  - coditsu
  - test
